name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Install dependencies
        run: flutter pub get
        
      - name: Patch legacy AGP plugins
        run: |
          sed -i 's/android {/android {\n    namespace "appmire.be.flutterjailbreakdetection"/g' ~/.pub-cache/hosted/pub.dev/flutter_jailbreak_detection-*/android/build.gradle
          cat << 'EOF' >> ~/.pub-cache/hosted/pub.dev/flutter_jailbreak_detection-*/android/build.gradle
          
          android {
              compileOptions {
                  sourceCompatibility JavaVersion.VERSION_17
                  targetCompatibility JavaVersion.VERSION_17
              }
          }
          tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).configureEach {
              kotlinOptions {
                  jvmTarget = "17"
              }
          }
          EOF
          
      - name: Build APK (with Military-Grade Obfuscation)
        run: flutter build apk --release --obfuscate --split-debug-info=build/app/outputs/symbols
        continue-on-error: false
        
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: KiddoCab-APK
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Upload Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Build-Logs
          path: build_log.txt
